# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: socio
    build: .
    command: socio run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/socio.db
    volumes:
      - ./socio:/code/socio
      - ./db/:/db/
    ports:
      - "5000:5000"
